// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package repo

import (
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// CreateRepo serve caller to create an IRepo
func CreateRepo(logger *zap.Logger, rw *sqlx.DB) (IRepo, error) {
	iRepo := NewImpl(logger, rw)
	return iRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
