// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/godutch/internal/app/godutch"
	"github.com/blackhorseya/godutch/internal/app/godutch/api"
	"github.com/blackhorseya/godutch/internal/pkg/app"
	"github.com/blackhorseya/godutch/internal/pkg/entity/config"
	"github.com/blackhorseya/godutch/internal/pkg/infra/databases"
	"github.com/blackhorseya/godutch/internal/pkg/infra/idgen"
	"github.com/blackhorseya/godutch/internal/pkg/infra/log"
	"github.com/blackhorseya/godutch/internal/pkg/infra/token"
	"github.com/blackhorseya/godutch/internal/pkg/infra/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateApp serve caller to create an injector
func CreateApp(path2 string, nodeID int64) (*app.Application, error) {
	viper, err := config.New(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	godutchOptions, err := godutch.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	initHandlers := api.CreateInitHandlerFn()
	engine := http.NewRouter(httpOptions, logger, initHandlers)
	server, err := http.New(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	application, err := godutch.New(godutchOptions, logger, server)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(godutch.ProviderSet, log.ProviderSet, idgen.ProviderSet, config.ProviderSet, http.ProviderSet, databases.ProviderSet, token.ProviderSet, api.ProviderSet)
